website/website/apps/accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path , include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('website.apps.public.urls')),
    path("accounts/", include('website.apps.accounts.urls')),
]

website/website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInterest(models.Model):
    name = models.CharField(max_length = 64 , unique = True)
    normalized_name = models.CharField(max_length = 64 , unique = True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length = 64 , unique = True)
    normalized_name = models.CharField(max_length = 64 , unique = True)
    description = models.CharField(max_length = 200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):

    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name="profile")

    is_full_name_displayed = models.BooleanField(default=True)

    bio = models.CharField(max_length=500 , blank = True , null=True)
    website = models.URLField(max_length=250 , blank = True , null = True)
    person = models.ForeignKey(UserPersona , on_delete = models.SET_NULL , blank = True , null = True)
    interest = models.ManyToManyField(UserInterest , blank = True)

website/website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin,TemplateView):
    template_name = 'accounts/profile.html'

website/website/views.py
from django.shortcuts import render 
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    
    return render(request , 'index.html')

def about(request):
    
    return render(request , 'about.html')

def contact(request):
    
    return render(request , 'contact.html')

class ProfileView(LoginRequiredMixin,TemplateView):
    template_name = 'accounts/profile.html'

website/website/templates/about.html
{% extends 'base.html' %}

{% block title %} aboutpage {% endblock %}

{% block content %}
<h1>about page</h1>
{% endblock %}

website/website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Loginpage {% endblock %}

{% block content %}
<h1>Login</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login~</button>

</form>
{% endblock %}

website/website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}
<h1>
    {{ user.get_full_name }} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
    <h2>
        {{ profile.person|default:"" }}
    </h2>
    <div>
        {{ profile.bio|default:"" }}
    </div>
    <div>
        {% with website=profile.website|default:"" %}
            <a href="{{website}}">{{ website }}</a>
        {% endwith %}    
    </div>
    <div>
        Interests:
        {% for interest in profile.interest.all %}
            <span>
                {{ interest.name }}{% if not forloop.last %} , {% endif %}
            </span>
        {% endfor %}    
    </div>
    {% endif %}
{% endwith %}    
{% endblock %}

website/website/templates/base.html
<!DOCTYPE html>
<html>
<head>    
    <meta charset="utf-8">
    <title>{% block title %} kotnid {% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        {% block content %}
        {% endblock %}

    </main>
</body>
</html>

website/website/templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<h1>Contact page</h1>
{% endblock %}

website/website/templates/index.html
{% extends 'base.html' %}

{% block title %} homepage {% endblock %}

{% block content %}
<h1>Template page</h1>
{% endblock %}

website/website/templates/navbar.html
<div>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}home {% else %}<a href = "{{ index_url }}">home</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}about {% else %}<a href = "{{ about_url }}">about</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}contact {% else %}<a href = "{{ contact_url }}">contact</a>{% endif %}</span>

    <span style = "float: right">
        {% if user.is_authenticated %}
            <span> hi {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{% url 'accounts:profile' %}">profile</a>{% endif %}</span>
            <span><a href="{% url 'accounts:logout' %}">logout</a></span>
        {% else %}
            <span><a href="{% url 'accounts:login' %}">login</a></span> 
        {% endif %}
    </span>
</div>